sudo: required
language: go
services:
  - docker
script:
  - DEV_REGISTRY="docker.io" make docker-build
  - DEV_REGISTRY="docker.io" make test
notifications:
  slack:
    rooms:
      - drycc:xKmLlmJR4hfRAgVIOwdpAoC9#drycc
